# Generated by Django 5.0.6 on 2024-05-31 15:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MailingAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "last_attempt_datatime",
                    models.CharField(
                        max_length=200, verbose_name="дата и время последней попытки"
                    ),
                ),
                (
                    "attempt_status",
                    models.CharField(
                        choices=[("успешно", "успешно"), ("не успешно", "не успешно")],
                        max_length=200,
                        verbose_name="статус попытки ",
                    ),
                ),
                (
                    "mail_server_response",
                    models.TextField(
                        blank=True, null=True, verbose_name="ответ почтового сервера"
                    ),
                ),
            ],
            options={
                "verbose_name": "Попытка рассылки",
                "verbose_name_plural": "Попытки рассылок",
            },
        ),
        migrations.CreateModel(
            name="MailingSetting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "first_send_datetime",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="Дата и время первой отправки",
                    ),
                ),
                (
                    "periodicity",
                    models.CharField(
                        choices=[
                            ("ежедневно", "daily"),
                            ("еженедельно", "weekly"),
                            ("ежемесячно", "monthly"),
                        ],
                        default="ежедневно",
                        max_length=20,
                        verbose_name="Периодичность",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("создана", "создана"),
                            ("запущена", "запущена"),
                            ("завершена", "завершена"),
                        ],
                        default="создана",
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
            ],
            options={
                "verbose_name": "Настройка рассылки",
                "verbose_name_plural": "Настройки рассылок",
                "permissions": [
                    (
                        "can_change_status_mailingsetting",
                        "Can change status Настройка рассылки",
                    ),
                    ("can_view_mailingsetting", "Can view Настройка рассылки "),
                ],
            },
        ),
        migrations.CreateModel(
            name="MessageMailing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "letter_subject",
                    models.CharField(max_length=200, verbose_name="тема письма"),
                ),
                ("letter_body", models.TextField(verbose_name="тело письма")),
            ],
            options={
                "verbose_name": "Сообщение рассылки",
                "verbose_name_plural": "Сообщения рассылок",
            },
        ),
    ]
