# Generated by Django 5.0.6 on 2024-05-31 15:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('MailingSetting', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='mailingsetting',
            name='client',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='Клиент сервиса'),
        ),
        migrations.AddField(
            model_name='mailingattempt',
            name='mailingsetting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MailingSetting.mailingsetting', verbose_name='настройка рассылки'),
        ),
        migrations.AddField(
            model_name='messagemailing',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Клиент сервиса'),
        ),
        migrations.AddField(
            model_name='mailingsetting',
            name='message',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='MailingSetting.messagemailing', verbose_name='Сообщение рассылки'),
        ),
    ]
